export const portfolioData = [
  {
    name: "Tap Invest",
    // image: portfolioOne,
    logo: "/images/logo/tap.png",
    desc: "A leasing marketplace connecting investors with businesses, emphasizing transparency.",
    link: "https://tapinvest.in/",
  },
  {
    name: "Eye-My-Eye",
    logo: "/images/logo/eyeMyEye.png",
    desc: "Online eyewear retailer, EyeMyEye, provides affordable eyewear across India, featuring partnerships with brands like Polaroid, William Morris London, and Titan Eyewear.    ",
    link: "https://www.eyemyeye.com/",
  },
  {
    name: "Ken42",
    // image: portfolioTwo,
    logo: "/images/logo/ken42.png",
    desc: "Ken42 helps educational institutions cater to all their evolving needs from a single, unified platform that has been designed to help institutions. ",
    link: "https://www.ken42.com/",
  },
  {
    name: "Sheru",
    logo: "/images/logo/sheru.png",
    desc: "Leading renewable energy-based backend creation for transformative energy supply chain networks.    ",
    link: "https://sheru.se/",
  },
  {
    name: "Sivi",
    logo: "/images/logo/sivi.png",
    desc: " Sivi AI transforms text-based content into engaging visuals like banners and ads using advanced artificial intelligence. ",
    link: "https://sivi.ai/",
  },
  {
    name: "LXL Ideas",
    // image: portfolioOne,
    logo: "/images/logo/lxl.png",
    desc: "A tech solution for schools, fostering future-ready students through film pedagogy and skills development.",
    link: "https://www.lxl.in/",
  },
  {
    name: "Invincible Ocean",
    logo: "/images/logo/invincible.png",
    desc: " Invincible Ocean specializes in Digital Infrastructure, Cloud, Security, and Emerging Solutions, with in-house flagship products serving Fintech and Banking Industries.    ",
    link: "https://invincibleocean.com/",
  },
  {
    name: "Doqfy",
    // image: portfolioOne,
    logo: "/images/logo/Doqfy.png",
    desc: "A Contract Execution SaaS platform that provides secure, affordable, online legal ancillary services to businesses, professionals & individual users.",
    link: "https://doqfy.in/",
  },

  {
    name: "Sciative ",
    logo: "/images/logo/sciative.png",
    desc: " AI-powered cloud solutions automating pricing decisions and customer insights for business growth, serving clients in South Korea and India.    ",
    link: "https://sciative.com/",
  },
  {
    name: "Argoid ",
    logo: "/images/logo/argoid.png",
    desc: " Enhancing E-commerce and OTT user experiences with patented AI, boosting conversions, order value, and reducing bounce rates.    ",
    link: "https://www.argoid.ai/",
  },
  {
    name: "MentorMind",
    logo: "/images/logo/mentorMind.png",
    desc: " Online platform for real-world mentorship, enabling students & young professionals to engage with practical work scenarios.",
    link: "https://www.mentormind.in/",
  },
  {
    name: "optimile",
    logo: "/images/logo/optimile.png",
    desc: "Global logistics automation, optimizing supply chain among manufacturers, distribution centers, and warehouses through digital solutions.    ",
    link: "https://optimile.co/",
  },
  {
    name: "Tathya ",
    logo: "/images/logo/tathya.png",
    desc: "Tathya employs Machine Learning for real-time insights on Economic Indicators, such as Hot Metal production, Iron Ore inventory, and more. ",
    link: "https://www.tathya.earth/",
  },
  {
    name: "Kwiqreply",
    // image: portfolioThree,
    logo: "/images/logo/kwiqreply.png",
    desc: "An Omnichannel CRM designed for businesses seeking to place their customers at the centre and interact and engage with them effectively.  ",
    link: "https://www.kwiqreply.io/",
  },
  {
    name: "Snipe",
    logo: "/images/logo/snipe.png",
    desc: "Snipe drives engagement through gamified rewards, offering customized SDK and API products for brands and consumer platforms.",
    link: "https://playwithsnipe.com/",
  },
  {
    name: "Space Basic",
    // image: portfolioOne,
    logo: "/images/logo/spaceBasic.png",
    desc: "Enhances student housing communities with digital tools, serving 100K+ users across 50+ schools.",
    link: "https://www.spacebasic.com/",
  },
  {
    name: "Seminar Room",
    logo: "/images/logo/seminarRoom.png",
    desc: "Enhancing education by aligning academic curriculum with case studies, trends, and opportunities, offering Industry Expert Sessions to enhance student learning.",
    link: "https://www.seminarroom.in/",
  },

  {
    name: "Pichain",
    // image: portfolioFour,
    logo: "/images/logo/pichain.png",
    desc: "PiChain's deep tech systems simplify complex regulatory operations enabling automated compliance, onboarding and KYC. ",
    link: "https://www.pichainlabs.com/",
  },
  {
    name: "Ykrita Life Sciences",
    logo: "/images/logo/ykrita.png",
    desc: " Developing unique solutions to aid the rejuvenation of the natural liver. The aim of this project is to create a Bioengineered Artificial Ectopic Liver (BAEL) Device.  ",
    link: "https://ykrita.com/",
  },
  {
    name: "LearnCab",
    logo: "/images/logo/learncab.png",
    desc: " A leading digital education platform, specializing in CA, CS, and CMA courses, offering expertly crafted video lectures, adaptive learning, and content updates for professional students.",
    link: "https://www.learncab.com/",
  },
  {
    name: "Meolaa",
    logo: "/images/logo/meaolaa.png",
    desc: "A rapidly expanding, mission-driven e-commerce platform offering environmentally conscious, high-performance products that help bridge the gap between sustainability and lifestyle.",
    link: "https://meolaa.com/",
  },
  {
    name: "Flam",
    logo: "/images/logo/flam.png",
    desc: "An AI-powered, user-friendly platform that democratizes 3D XR content creation and camera-first consumption.",
    link: "https://flamapp.ai/",
  },
  {
    name: "Tohands",
    logo: "/images/logo/tohands.png",
    desc: "A smart calculator that transforms shopkeepers' financial processes, offering a comprehensive tool for intuitive tracking of income and expenditure.",
    link: "https://smart.tohands.in/",
  },
  {
    name: "PHYTunes",
    logo: "/images/logo/phytunes.png",
    desc: "Leverages Open RAN standards and cloud-based networks to optimize indoor connectivity with 5G and Wi-Fi 6 technologies",
    link: "https://www.phytunes.com/ ",
  },
  {
    name: "Covve",
    logo: "/images/logo/covve.png",
    desc: "A cloud-based personal relationship management platform that enables effective and personalized networking at scale",
    link: "https://covve.com/",
  },
  {
    name: "Anarchy Warzone",
    logo: "/images/logo/anarchy.png",
    desc: "India's first Mobile Third Person Shooter Battle Royale game with Web3 elements delivering a fusion of traditional gameplay and blockchain-based asset ownership",
    link: "https://www.anarchy.game/",
  },
  {
    name: "Altco",
    logo: "/images/logo/altco.png",
    desc: "Uses ethically-sourced plant ingredients, and is dedicated to providing accessible, affordable, and nourishing vegan alternatives",
    link: "https://alt.company/",
  },
  {
    name: "Medpay",
    logo: "/images/logo/medpay.png",
    desc: "Organizing the outpatient market in India by building the digital infrastructure for offline centers and making them e-Commerce ready",
    link: "https://www.medpay.in/",
  },
  {
    name: "Gestalt",
    logo: "/images/logo/gestalt.png",
    desc: "An AI-powered data warehouse solution specifically designed for lenders, unifying disparate data sources into a single source of truth.",
    link: "https://gestalttech.com/",
  },
  {
    name: "OTO Capital",
    logo: "/images/logo/oto-capital.png",
    desc: "India's leading platform that facilitates two wheeler loans at upto 35% lower EMIs than banks",
    link: "https://www.otocapital.in/",
  },
  {
    name: "Kennovate",
    logo: "/images/logo/kennovate.png",
    desc: "Kennovate is a comprehensive and collaborative digital platform which designed to manage the end to end incubation, innovation and investment operations of an organization.",
    link: "https://kennovate.com/",
  },
];
