export const clientLogo: string[] = [
  "/images/logo/mentorMind.png",
  "/images/logo/optimile.png",
  "/images/logo/argoid.png",
  "/images/logo/snipe.png",
  "/images/logo/ykrita.png",
  // kidaura "/images/logo/.png",
  "/images/logo/doqfy.png",
  "/images/logo/seminarRoom.png",
  "/images/logo/invincible.png",
  "/images/logo/sciative.png",
  "/images/logo/eyeMyEye.png",
  "/images/logo/sheru.png",
  "/images/logo/kahanibox.png",
  "/images/logo/ken42.png",
  "/images/logo/learncab.png",
  "/images/logo/sivi.png",
];
